### ISSUE TITLE
大佬 求教一下nodejs 或者 Python 怎么读取com.apple.dt.xcode.sfl2的内容 谢谢

### ISSUE THREAD

**Issue by JoysKang** [dacaiguoguo/XcodeRecentManager#1]
我这边实现对于路径读取总是乱码，不会 object-c 看的不是很明白，想请教下
我实现的node代码如下
```javascript
const bplist = require('bplist-parser');


const fileName = "/Users/joys/Library/Application\ Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.apple.dt.xcode.sfl2";


function ab2str(buf) {
    return String.fromCharCode.apply(null, new Uint16Array(buf));
}

(async () => {
    let data = await bplist.parseFile(fileName);
    data = JSON.parse(JSON.stringify(data));
    const index = data[0].$objects.findIndex((element, index) => {
        if (typeof element == 'object' && element['type'] === 'Buffer') {
            return true
        }
    })

    const arrayBuffer = data[0].$objects[index].data
    console.log(ab2str(arrayBuffer))
})();
```

读取结果
book 0ø Usersjoys       Downloadslearn.playground ,î!Êlap  AÃ[awjoysfanõ     file:///
                                                                                        Macintosh H  hAÁÞD$A87A9DFF-2EA0-4F9F-992F-84E5113BF2B9 ï/NSURLDocumentIdentifierKeyÃðþÿÿÿX°Ø@È ´ $ 4 h H X   0 ÀÀøÀÐð@ÀÈ

**Comment by dacaiguoguo** [comment]
先执行命令把格式转换一下,试试看
`plutil -convert xml1 $plistpath -o $plistpath`

**Comment by dacaiguoguo** [comment]
数据解析除了Objective-C还有C的。有空了，用node调用麻烦了。

**Comment by JoysKang** [comment]
![image](https://user-images.githubusercontent.com/11786681/129333275-030b352c-af7c-47d4-a9ef-a1b646633619.png)
编码转了之后，地址还是不知道怎么处理？  其他部分没问题  data /data 之间的数据

**Comment by dacaiguoguo** [comment]
![image](https://user-images.githubusercontent.com/2638446/129348189-ed56c1c5-68f9-4c1e-8b27-7eceb4d558f5.png)

https://github.com/dacaiguoguo/XcodeRecentManager/blob/main/XcodeRecentManager.js

**Comment by JoysKang** [comment]
objc 只能在 node < 12 的情况下使用  如果node >= 12 就无法使用了 
![image](https://user-images.githubusercontent.com/11786681/129369025-d131658a-c73f-4d82-9ca7-a19b200baa1d.png)

**Comment by JoysKang** [comment]
> objc 只能在 node < 12 的情况下使用 如果node >= 12 就无法使用了
> ![image](https://user-images.githubusercontent.com/11786681/129369025-d131658a-c73f-4d82-9ca7-a19b200baa1d.png)

或许可以考虑直接生成一个可执行文件  然后输出  然后在node

**Comment by JoysKang** [comment]
另外再厚颜问下  这个对象怎么转成js对象呢？
![image](https://user-images.githubusercontent.com/11786681/129376253-ba16d5c5-2fc2-44ee-9ffa-df6b79b05ba0.png)

**Comment by dacaiguoguo** [comment]
`    console.log(String(receurl))`

**Comment by JoysKang** [comment]
> > objc 只能在 node < 12 的情况下使用 如果node >= 12 就无法使用了
> > ![image](https://user-images.githubusercontent.com/11786681/129369025-d131658a-c73f-4d82-9ca7-a19b200baa1d.png)
> 
> 或许可以考虑直接生成一个可执行文件 然后输出 然后在node

使用 nexe 生成了二进制文件 调用正常  感谢大佬的支持  谢谢
